// Auto-generated by `supabase gen types typescript --local`.
// Regenerate after every migration: pnpm db:types
//
// Placeholder until the local Supabase instance is running.
// Run `supabase start` then `pnpm db:types` to populate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
